// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'grouptag-menu-assign-existing'
  | 'grouptag-menu-assign-new'
  | 'grouptag-menu-delete-group'
  | 'grouptag-menu-recolor-group'
  | 'grouptag-menu-remove-from-group'
  | 'grouptag-menu-rename-group'
  | 'grouptag-toolbar-label';
